theme: jekyll-theme-minimal
title: BigDipper Read API
description: Read various documents from Image using BigDipper API
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  is_project_page: false